---
# 1. Generate the configuration
# -----------------------------------------------------------------------------
- name: Lookup sls.ibm.com/v1.LicenseService
  k8s_info:
    api_version: sls.ibm.com/v1
    kind: LicenseService
    name: "{{ sls_instance_name }}"
    namespace: "{{ sls_namespace }}"
  register: sls_cr_result

- name: Obtain License Service Certificate
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ sls_cr_result.resources[0].status.ca.secretName }}"
    namespace: "{{ sls_namespace }}"
  register: _sls_ca

- name: Set facts for SLSCfg
  set_fact:
    sls_registration_key: "{{sls_cr_result.resources[0].status.registrationKey}}"
    sls_url: "{{sls_cr_result.resources[0].status.url}}"
    sls_tls_crt: "{{_sls_ca.resources[0].data['ca.crt'] | b64decode }}"


# 2. Write out the config to the local filesystem
# -----------------------------------------------------------------------------
- name: Copy SLSCfg to filesytem
  ansible.builtin.template:
    src: slscfg.yml.j2
    dest: "{{ mas_config_dir }}/sls-{{ sls_instance_name | lower }}-{{ sls_namespace }}.yml"
