galaxy_info:
  author: David Parker (@durera)
  description: Install an operator, supports both pre-release and released operator installation (access to pre-release operator builds is limited)
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops

dependencies: []
