---
# Main Catalog: MAS
# -----------------------------------------------------------------------------
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-mas-operators
  namespace: openshift-marketplace
spec:
  displayName: IBM MAS Catalog (Dev)
  publisher: IBM
  description: Catalog Source for IBM Maximo Application Suite (Internal Use Only)
  sourceType: grpc
  image: wiotp-docker-local.artifactory.swg-devops.com/cpopen/ibm-mas-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# Main Catalog: Truststore Manager
# -----------------------------------------------------------------------------
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-truststore-mgr-operators
  namespace: openshift-marketplace
spec:
  displayName: IBM Truststore Manager Catalog (Dev)
  publisher: IBM
  description: Catalog Source for IBM Truststore Manager (Internal Use Only)
  sourceType: grpc
  image: wiotp-docker-local.artifactory.swg-devops.com/cpopen/ibm-truststore-mgr-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# Application Catalog: IoT
# -----------------------------------------------------------------------------
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-mas-iot-operators
  namespace: openshift-marketplace
spec:
  displayName: "IBM MAS: IoT Catalog (Dev)"
  publisher: IBM
  description: "Catalog Source for IBM MAS: IoT application (Internal Use Only)"
  sourceType: grpc
  image: wiotp-docker-local.artifactory.swg-devops.com/cpopen/ibm-mas-iot-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# Application Catalog: Manage
# -----------------------------------------------------------------------------
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-mas-manage-operators
  namespace: openshift-marketplace
spec:
  displayName: "IBM MAS: Manage Catalog (Dev)"
  publisher: IBM
  description: "Catalog Source for IBM MAS: Manage application (Internal Use Only)"
  sourceType: grpc
  image: wiotp-docker-local.artifactory.swg-devops.com/cpopen/ibm-mas-manage-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# Main Catalog: SLS
# -----------------------------------------------------------------------------
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-sls-operators
  namespace: openshift-marketplace
spec:
  displayName: IBM SLS Catalog (Dev)
  publisher: IBM
  description: "Catalog Source for IBM Suite Licensing Service (Internal Use Only)"
  sourceType: grpc
  image: wiotp-docker-local.artifactory.swg-devops.com/cpopen/ibm-sls-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
