---
# tasks file for suite

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if mas_instance_id is not provided"
  when: mas_instance_id is not defined or mas_instance_id == ""
  fail:
    msg: "mas_instance_id property is required"


# 2. Configure target namespace
# -----------------------------------------------------------------------------
- name: "Configure namespace"
  set_fact:
    mas_namespace: "mas-{{ mas_instance_id }}-core"


# # 3. Follow Suite Status
# # -----------------------------------------------------------------------------
# - name: "Wait for Suite to be ready (60s delay)"
#   community.kubernetes.k8s_info:
#     api_version: v1
#     name: "{{mas_instance_id}}"
#     namespace: "{{mas_namespace}}"
#     kind: Suite
#   register: suite_cr_result
#   until:
#     - suite_cr_result.resources[0].status is defined
#     - suite_cr_result.resources[0].status.conditions | length == 5
#     - suite_cr_result.resources[0].status.conditions[0].status == 'True'
#     - suite_cr_result.resources[0].status.conditions[1].status == 'True'
#     - suite_cr_result.resources[0].status.conditions[2].status == 'True'
#     - suite_cr_result.resources[0].status.conditions[3].status == 'True'
#   retries: 30 # approx 30 minutes before we give up
#   delay: 60 # 1 minute


# 4. Lookup for superuser credentials
# -----------------------------------------------------------------------------
- name: "Lookup MAS superuser credentials"
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ mas_instance_id }}-credentials-superuser"
    namespace: "{{mas_namespace}}"
  register: superuser_credentials


# 5. Print MAS login information
# -----------------------------------------------------------------------------
- name: Lookup Route for admin
  community.kubernetes.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: "{{ mas_instance_id}}-admin"
    namespace: "{{ mas_namespace }}"
  register: admin_route

- name: "Lookup cluster subdomain"
  community.kubernetes.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: cluster_subdomain

# - debug:
#     msg:
#       - "Maximo Application is Ready, use the superuser credentials to authenticate"
#       - "Superuser Credentials:"
#       - "Username: .... {{ superuser_credentials.resources[0].data.username | b64decode }}"
#       - "Password: .... {{ superuser_credentials.resources[0].data.password | b64decode }}"
#       - "Admin Url: ... {{ admin_route.resources[0].spec.host}}"
