---
# Application specific variables for Manage
mas_app_fqn: iots.iot.ibm.com
mas_app_api_version: iot.ibm.com/v1
mas_app_kind: IoT
mas_app_spec:
  bindings:
    jdbc: system
    mongo: system
    kafka: system
