---
# 1. aws Login
# -----------------------------------------------------------------------------
- name: "login-aws : Oc Login the created cluster"
  vars:
    login_password: "{{ lookup('env', 'OPENSHIFT_PASSWORD') | default('', True) }}"
    login_server: "https://api.{{ lookup('env', 'CLUSTER_NAME') | default('', True) }}.{{ lookup('env','BASE_DOMAIN') }}:6443"
    login_user: "{{ lookup('env', 'OPENSHIFT_USER') | default('', True) }}"
  shell: |
    oc login -u {{login_user}} -p {{ login_password }} --server={{ login_server }} --insecure-skip-tls-verify=true
    