apiVersion: metaoperator.cpd.ibm.com/v1
kind: CPDService
metadata:
  name: "cpdservice-{{service_name}}"
  namespace: "{{ cpd_meta_namespace }}"
spec:
  license:
    accept: true
  serviceName: "{{service_name}}"
  storageClass: "{{ cpd_storage_class }}"
  version: latest
