---

# Fail if no entitlement key is provided
# -----------------------------------------------------------------------------
- name: "Fail if cpd_registry_password has not been provided"
  when: cpd_registry_password is not defined or cpd_registry_password == ""
  fail:
    msg: "cpd_registry_password property has not been set"

- name: "Debug information"
  debug:
    msg:
      - "CPD registry ................. {{ cpd_registry }}"
      - "CPD username ................. {{ cpd_registry_user }}"
      - "CPD entitlement .............. *********************"
      - "Namespace .................... {{ cpd_meta_namespace }}"


# 1. Setup namespace for CP4D
# -----------------------------------------------------------------------------
- name: "Create CPD Meta Namespace"
  vars:
    namespace: "{{cpd_meta_namespace}}"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/namespace.yaml') }}"
  register: _cpd_meta_namespace_result


# 2. Setup entitlement for CP4D
# -----------------------------------------------------------------------------
- name: "Create ibm-entitlement-key secret"
  vars:
    entitledAuthStr: "{{cpd_registry_user}}:{{cpd_registry_password}}"
    entitledAuth: "{{ entitledAuthStr | b64encode }}"
    content:
      - "{\"auths\":{\"{{cpd_registry}}\":{\"username\":\"{{cpd_registry_user}}\",\"password\":\"{{cpd_registry_password}}\",\"auth\":\"{{entitledAuth}}\"}"
      - "}"
      - "}"
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: ibm-entitlement-key
        namespace: "{{ cpd_meta_namespace }}"
      stringData:
        .dockerconfigjson: "{{ content | join('') | string }}"


# 3. Install CP4D operator
# -----------------------------------------------------------------------------
- name: "Install CPD Subscription"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/subscription.yaml') }}"
  register: _cpd_subscription_result

- name: "Wait for CP4D operator to be ready (60s delay)"
  community.kubernetes.k8s_info:
    api_version: v1
    name: ibm-cp-data-operator
    namespace: "{{cpd_meta_namespace}}"
    kind: Deployment
  register: _cpd_subscription
  until: _cpd_subscription.resources[0].status.availableReplicas is defined
  retries: 10 # Approximately 10 minutes before we give up
  delay: 60 # 1 minute
