---
# 1. Provide debug information to the user
# -----------------------------------------------------------------------------
- name: "Debug information"
  debug:
    msg:
      - "Namespace .................... {{ cpd_meta_namespace }}"
      - "Storage class ................ {{ cpd_storage_class }}"
      - "Db2 database instanceId ...... {{ db2wh_instance_id }}"
      - "Db2 database name ............ {{ db2wh_dbname }}"
      - "Db2 database username ........ {{ db2wh_username }}"
      - "Db2 version .................. {{ db2wh_version }}"
      - "MAS Instance ID .............. {{ mas_instance_id }}"
      - "MAS Config directory ......... {{ mas_config_dir }}"

# 2. Create a Db2 instance
# -----------------------------------------------------------------------------
- name: "Create db2wh instance"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/db2ucluster.yaml') }}"
  register: _db2_cluster_result

# Wait for the cluster to be ready
- name: "Wait for db2wh instance to be ready (5m delay)"
  community.kubernetes.k8s_info:
    api_version: db2u.databases.ibm.com/v1
    name: "{{ db2wh_instance_id | lower }}"
    namespace: "{{cpd_meta_namespace}}"
    kind: Db2uCluster
  register: db2_cluster_lookup
  until:
    - db2_cluster_lookup.resources | length == 1
    - db2_cluster_lookup.resources[0].status.state == "Ready"
  retries: 24 # Approximately 2 hours before we give up
  delay: 300 # 5 minutes


# 3. Configure a public route for Db2
# -----------------------------------------------------------------------------
- name: "Get cluster subdomain"
  community.kubernetes.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: _cluster_subdomain

- name: Lookup db2wh TLS certificates
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    name: "internal-tls"
    namespace: "{{cpd_meta_namespace}}"
  register: _db2u_instance_certificates

- name: Lookup db2wh Engn Service
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Service
    name: "c-{{db2wh_instance_id | lower}}-db2u-engn-svc"
    namespace: "{{cpd_meta_namespace}}"
  register: _db2u_instance_engn_svc
  until:
    - _db2u_instance_engn_svc.resources[0] is defined
  retries: 15 # approx 5 minutes before we give up
  delay: 20

- name: Set Db2wh certificates as Facts
  set_fact:
    # We need to use certificate.pem rather than tls.crt when we create the JdbcCfg for MAS
    db2wh_pem: "{{ _db2u_instance_certificates.resources[0].data['certificate.pem'] | b64decode }}"
    db2wh_tls_crt: "{{ _db2u_instance_certificates.resources[0].data['tls.crt'] | b64decode }}"
    db2wh_tls_key: "{{ _db2u_instance_certificates.resources[0].data['tls.key'] | b64decode }}"
  when:
    - _db2u_instance_certificates is defined
    - (_db2u_instance_certificates.resources | length > 0)

- name: Set Db2wh TLS nodePort
  set_fact:
    db2wh_tls_nodeport: "{{item.nodePort}}"
  when: "{{item.name == 'ssl-server'}}"
  loop:
    "{{_db2u_instance_engn_svc.resources[0].spec.ports}}"


- name: "Create Db2 Warehouse route"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/tlsroute.yml') }}"


# 3. Generate a JdbcCfg for MAS configuration
# -----------------------------------------------------------------------------
- include_tasks: tasks/suite_jdbccfg.yml
  when:
    - mas_instance_id is defined
    - mas_instance_id != ""
    - mas_config_dir is defined
    - mas_config_dir != ""
