---
- name: Lookup db2wh instance password
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    name: "c-{{db2wh_instance_id | lower }}-instancepassword"
    namespace: "{{cpd_meta_namespace}}"
  register: _db2u_instance_password

- name: Set Facts for JdbcCfg
  set_fact:
    jdbc_instance_password: "{{ _db2u_instance_password.resources[0].data.password | b64decode }}"
    jdbc_url: "jdbc:db2://{{db2wh_instance_id | lower }}-{{cpd_meta_namespace}}.{{_cluster_subdomain.resources[0].spec.domain}}:{{db2wh_tls_nodeport}}/{{db2wh_dbname}}:sslConnection=true;"

- name: Copy JdbcCfg to filesytem
  ansible.builtin.template:
    src: suite_jdbccfg.yml
    dest: "{{ mas_config_dir }}/jdbc-{{ db2wh_instance_id | lower }}-{{ cpd_meta_namespace }}.yml"
