apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  name: "{{ db2wh_instance_id | lower }}"
  namespace: "{{ cpd_meta_namespace }}"
spec:
  account:
    privileged: true
  addOns:
    graph: {}
    rest: {}
  advOpts:
    db2SecurityPlugin: cloud_gss_plugin
  version: "{{ db2wh_version }}"
  size: 1
  environment:
    database:
      name: "{{db2wh_dbname}}"
      ssl:
        secretName: "internal-tls"
        certLabel: "CN=zen-ca-cert"
      settings:
        dftTableOrg: ROW
    dbType: db2wh
    instance:
      dbmConfig:
        SRVCON_PW_PLUGIN: IBMIAMauthpwfile
        group_plugin: IBMIAMauthgroup
        srvcon_auth: GSS_SERVER_ENCRYPT
        srvcon_gssplugin_list: IBMIAMauth
      registry:
        DB2_4K_DEVICE_SUPPORT: "ON"
        DB2_FMP_RUN_AS_CONNECTED_USER: "NO"
        DB2_WORKLOAD: ANALYTICS
        DB2AUTH: OSAUTHDB,ALLOW_LOCAL_FALLBACK,PLUGIN_AUTO_RELOAD
  license: {}
  podConfig:
    db2u:
      resource:
        db2u:
          limits:
            cpu: 2
            memory: 16Gi
  storage:
    - name: share
      type: "create"
      spec:
        storageClassName: "{{ cpd_storage_class }}"
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 100Gi
