---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "jdbc-{{ db2wh_instance_id | lower }}-credentials"
  namespace: "mas-{{mas_instance_id}}-core"
stringData:
  username: "{{db2wh_username}}"
  password: "{{jdbc_instance_password}}"
---
apiVersion: config.mas.ibm.com/v1
kind: JdbcCfg
metadata:
  name: "{{mas_instance_id}}-jdbc-system"
  namespace: "mas-{{mas_instance_id}}-core"
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: "{{mas_instance_id}}"
spec:
  displayName: "{{ db2wh_instance_id | lower }} on CP4D"
  config:
    url: "{{ jdbc_url }}"
    sslEnabled: true
    credentials:
      secretName: "jdbc-{{ db2wh_instance_id | lower }}-credentials"
  certificates:
    - alias: "{{ db2wh_instance_id | lower }}"
      crt: |
        {{ db2wh_pem | indent(8) }}
