---
- hosts: localhost
  any_errors_fatal: true
  vars:
    db_instance_id: "{{ lookup('env', 'DB_INSTANCE_ID') | default('dbinst', True) }}"
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
    db_username: "{{ lookup('env', 'MAS_DB_USER') }}"
    jdbc_instance_password: "{{ lookup('env', 'MAS_DB_PASSWORD') }}"
    jdbc_url: "{{ lookup('env', 'MAS_JDBC_URL') }}"
    db_pem_file: "{{ lookup('env', 'MAS_JDBC_CERT_LOCAL_FILE') }}"

  roles:
    - suite_db_config
