---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # Choose which catalog source to use for the MAS install, default to the IBM operator catalog
    mas_catalog_source: "{{ lookup('env', 'MAS_CATALOG_SOURCE') | default('ibm-operator-catalog', true) }}"

    # --- Dev catalog settings ----------------------------------------------------------------------------------------
    # Only required when using the development catalog sources for pre-release installation
    # These are used to set up image pull secret in the openshift-marketplace namespace
    artifactory_username: "{{ lookup('env', 'W3_USERNAME') | lower }}"
    artifactory_apikey: "{{ lookup('env', 'ARTIFACTORY_APIKEY') }}"
    # -----------------------------------------------------------------------------------------------------------------

    # Which MAS channel to subscribe to
    mas_channel: "{{ lookup('env', 'MAS_CHANNEL') | default('8.x', true) }}"

    # MAS configuration
    custom_domain: "{{ lookup('env', 'MAS_DOMAIN') | default(None)}}"
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
    mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"

    # MAS configuration - IBM container registry configuration
    # Set both of these to wiotp-docker-local.artifactory.swg-devops.com for dev
    mas_icr_cp: "{{ lookup('env', 'MAS_ICR_CP') | default('cp.icr.io/cp', true) }}"
    mas_icr_cpopen: "{{ lookup('env', 'MAS_ICR_CPOPEN') | default('icr.io/cpopen', true) }}"

    # MAS configuration - Entitlement
    mas_entitlement_username: "{{ lookup('env', 'MAS_ENTITLEMENT_USERNAME') | default('cp', true) }}"
    mas_entitlement_key: "{{ lookup('env', 'MAS_ENTITLEMENT_KEY') }}"

    #####################################################################################################
    ##################                       DNS Configuration                     ######################
    #####################################################################################################
    # you can obtain CRN from overview page of your CIS service in IBM Cloud
    cis_crn: "{{ lookup('env', 'CIS_CRN') }}"
    # Domain prefix is whatever you want to append to your DNS entry to make it unique
    cis_subdomain: "{{ lookup('env', 'CIS_SUBDOMAIN') }}"
    # generate your apikey in IBM Cloud
    ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"

    # Email used register letsencrypt certificates and receive cert notifications
    cis_email: "{{ lookup('env', 'CIS_EMAIL') }}"
    # Skip DNS entries creation
    cis_skip_dns_entries: "{{ lookup('env', 'CIS_SKIP_DNS_ENTRIES') | default(false, true) }}"
    # Skip CIS cluster issuer creation, in case you just want to create the DNS entries
    cis_skip_cluster_issuer: "{{ lookup('env', 'CIS_SKIP_CLUSTER_ISSUER') | default(false, true) }}"
    # Do you want to update a DNS entry if it already exists?
    update_dns: "{{ lookup('env', 'UPDATE_DNS_ENTRIES') | default(true, true) }}"
    # e.g: "apps.joaopauloksn.cp.fyre.ibm.com" Default will be always from cluster ingress CR.
    custom_ocp_ingress: "{{ lookup('env', 'OCP_INGRESS') | default(None, true)}}"

    # If cis, custom_cluster_issuer = cis-letsencrypt-production-{{ mas_instance_id }}
    # If PKI, custom_cluster_issuer = MAS_CUSTOM_CLUSTER_ISSUER
    # If not specified, custom_cluster_issuer = autogenerated
    default_custom_cluster_issuer: "'cis-letsencrypt-production-{{ mas_instance_id }}"
    custom_cluster_issuer: "{{ (cis_crn != '') | ternary (lookup('env', 'MAS_CUSTOM_CLUSTER_ISSUER') | default(default_custom_cluster_issuer, true), lookup('env', 'MAS_CUSTOM_CLUSTER_ISSUER') | default(None, true)) }}"
    certificate_duration: "{{ lookup('env', 'CERTIFICATE_DURATION') | default('8760h0m0s', true) }}"
    certificate_renew_before: "{{ lookup('env', 'CERTIFICATE_RENEW_BEFORE') | default('720h0m0s', true) }}"

    # Only required for airgap variation:
    mas_catalog_image: "{{ lookup('env', 'MAS_CATALOG_IMG') }}"
    tm_catalog_image: "{{ lookup('env', 'TM_CATALOG_IMG') }}"

    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

  roles:
    - suite_dns
    - suite_install
    - suite_config
    - suite_verify
