---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # Define the version of SLS will be installed
    sls_catalog_source: "{{ lookup('env', 'SLS_CATALOG_SOURCE') | default('ibm-operator-catalog', true) }}"
    sls_channel: "{{ lookup('env', 'SLS_CHANNEL') | default('3.x', true) }}"

    # Define where SLS will be installed
    sls_namespace: "{{ lookup('env', 'SLS_NAMESPACE') | default('ibm-sls', true) }}"
    sls_icr_cp: "{{ lookup('env', 'SLS_ICR_CP') | default('cp.icr.io/cp', true) }}"
    sls_icr_cpopen: "{{ lookup('env', 'SLS_ICR_CPOPEN') | default('icr.io/cpopen', true) }}"

    sls_instance_name: "{{ lookup('env', 'SLS_INSTANCE_NAME') | default('sls', true) }}"
    
    # IBM entitlement key for SLS
    sls_entitlement_username: "{{ lookup('env', 'SLS_ENTITLEMENT_USERNAME') | default('cp', true) }}"
    sls_entitlement_key: "{{ lookup('env', 'SLS_ENTITLEMENT_KEY') }}"

    # MAS instance configuration
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

    # SLS settings
    sls_storage_class: "{{ lookup('env', 'SLS_STORAGE_CLASS') }}"
    sls_domain: "{{ lookup('env', 'SLS_DOMAIN') }}"
    sls_auth_enforce: "{{ lookup('env', 'SLS_AUTH_ENFORCE') | default('True', true) | bool }}"
    sls_compliance_enforce: "{{ lookup('env', 'SLS_COMPLIANCE_ENFORCE') | default('True', true) | bool }}"
    sls_registration_open: "{{ lookup('env', 'SLS_REGISTRATION_OPEN') | default('True', true) | bool }}"

    # Destination for the generated MAS SlsCfg resource template
    sls_cfg_file: "{{ mas_config_dir }}/sls.yml"

    # configuration file for 
    mongodb_cfg_file: "{{mas_config_dir}}/mongo-{{ lookup('env', 'MONGODB_NAMESPACE') }}.yml"

    # Bootstrap is used to initialize SLS, provide if you have an existing lic file and licenseId
    bootstrap:
      license_id: "{{ lookup('env', 'SLS_LICENSE_ID') | default('', true) }}"
      registration_key: "{{ lookup('env', 'SLS_REGISTRATION_KEY') | default('', true) }}"
      entitlement_file: "{{mas_config_dir}}/entitlement.lic"
  roles:
    - sls_install
