- hosts: localhost
  any_errors_fatal: true
  vars:
    kafka_namespace: "{{ lookup('env', 'KAFKA_NAMESPACE') }}"
    kafka_cluster_name: "{{ lookup('env', 'KAFKA_CLUSTER_NAME') }}"
    kafka_cluster_size: "{{ lookup('env', 'KAFKA_CLUSTER_SIZE') }}"
    kafka_storage_class: "{{ lookup('env', 'KAFKA_STORAGE_CLASS') }}"
    kafka_user_name: "{{ lookup('env', 'KAFKA_USER_NAME') }}"
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
  roles:
    - amqstreams
