---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # BAS Configuration
    bas_namespace: "{{ lookup('env', 'BAS_NAMESPACE') | default('ibm-bas', true) }}"
    bas_persistent_storage: "{{ lookup('env', 'BAS_PERSISTENT_STORAGE') | default('', true) }}"
    bas_meta_storage_class: "{{ lookup('env', 'BAS_META_STORAGE') | default('', true) }}"

    bas_username: "{{ lookup('env', 'BAS_USERNAME') | default('basuser', true) }}"
    bas_password: "{{ lookup('env', 'BAS_PASSWORD') | default('password', true) }}"

    grafana_username: "{{ lookup('env', 'GRAPHANA_USERNAME') | default('basuser', true) }}"
    grafana_password: "{{ lookup('env', 'GRAPHANA_PASSWORD') | default('password', true) }}"
    contact:
      email: "{{ lookup('env', 'BAS_CONTACT_MAIL') | default('john@mycompany.com', true) }}"
      firstName: "{{ lookup('env', 'BAS_CONTACT_FIRSTNAME') | default('John', true) }}"
      lastName: "{{ lookup('env', 'BAS_CONTACT_LASTNAME') | default('Barnes', true) }}"

    # MAS Configuration
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

  roles:
  - bas_install
