---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-ca-crt
  namespace: "{{mongodb_namespace}}"
spec:
  isCA: true
  commonName: mongo-ca-crt 
  secretName: mongo-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  
  dnsNames:
  - "*.mas-mongo-ce-svc.{{mongodb_namespace}}.svc.cluster.local"
  - "127.0.0.1"
  - "localhost"

  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io
