apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-client
  namespace: "{{mongodb_namespace}}"
spec:
  dnsNames:
  - "*.mas-mongo-ce-svc.{{mongodb_namespace}}.svc.cluster.local"
  - "127.0.0.1"
  - "localhost"
  issuerRef:
    name: mongo-issuer
  secretName: mongo-client-cert
