---
- name: "Debug information"
  debug:
    msg:
      - "CIS CRN ...................... {{ cis_crn }}"

# 1. Set up the OCP ingress for DNS entries
# -----------------------------------------------------------------------------
- name: "Get cluster subdomain"
  community.kubernetes.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: _cluster_subdomain

- name: "Configure ingress"
  set_fact:
    ocp_ingress: "{{ (custom_ocp_ingress != '') | ternary (custom_ocp_ingress, 'cis-proxy-route.' ~ _cluster_subdomain.resources[0].spec.domain) }}"

- name: Create k8s resources for cis webhook
  when:
    - ibmcloud_apikey is defined
    - cis_crn is defined
  community.kubernetes.k8s:
    namespace: "{{ certManager.namespace }}"
    state: present
    definition: "{{ lookup('template', item) }}"
  with_items:
    - templates/cis/rbac.yml.j2
    - templates/cis/pki.yml.j2
    - templates/cis/deployment.yml.j2
    - templates/cis/apiservice.yml.j2
    - templates/cis/service.yml.j2
    - templates/cis/cis-apikey-secret.yml.j2
    - templates/cis/staging-cert.yml.j2
    - templates/cis/production-cert.yml.j2
    - templates/cis/cis-proxy-route.yml.j2
