---
- include_tasks: tasks/providers/cis/main.yml
  when:
    - custom_domain != ""
    - custom_cluster_issuer != ""
    - cis_crn is defined
    - cis_email is defined
    - ibmcloud_apikey is defined
