apiVersion: bas.ibm.com/v1
kind: FullDeployment
metadata:
  name: fulldeployment
  namespace: "{{bas_namespace}}"
spec:
  allowed_domains: "*"
  db_archive:
    frequency: '@monthly'
    retention_age: 6
    persistent_storage:
      storage_class: "{{bas_persistent_storage}}"
      storage_size: 10G
  airgapped:
    enabled: 'false'
    backup_deletion_frequency: '@daily'
    backup_retention_period: 7
  event_scheduler_frequency: '*/10 * * * *'
  ibmproxyurl: 'https://iaps.ibm.com'
  image_pull_secret: bas-images-pull-secret
  postgres:
    storage_class: "{{bas_meta_storage_class}}"
    storage_size: 10G
  kafka:
    storage_class: "{{bas_meta_storage_class}}"
    storage_size: 5G
    zookeeper_storage_class: "{{bas_meta_storage_class}}"
    zookeeper_storage_size: 5G
  prometheus_scheduler_frequency: '@daily'
  prometheus_metrics: []
  env_type: lite
