---
# 1. Provide debug information to the user
# -----------------------------------------------------------------------------
- name: "Debug information"
  debug:
    msg:
      - "Namespace .................... {{ cpd_meta_namespace }}"
      - "Storage class ................ {{ cpd_storage_class }}"
      - "CP4D services ................ {{ cpd_services }}"


# 2. Install CP4D Services
# -----------------------------------------------------------------------------
- name: "Install CPDServices"
  vars:
    service_name: "{{ item }}"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/cpdservice.yml') }}"
  with_items: "{{ cpd_services }}"


# 3. Wait for CP4D Services to be ready
# -----------------------------------------------------------------------------
- include_tasks: wait_for_services.yml


# 4. Provide CP4D dashboard URL
# -----------------------------------------------------------------------------
- name: "Obtain CP4D dashboard URL"
  community.kubernetes.k8s_info:
    api_version: v1
    name: "{{ cpd_meta_namespace }}-cpd"
    namespace: "{{cpd_meta_namespace}}"
    kind: Route
  register: cpd_route_lookup

- debug:
    msg:
      - "CP4D Dashboard ................. https://{{cpd_route_lookup.resources[0].spec.host}}"
      - "CP4D Username .................. admin"
      - "CP4D Password .................. password"
