---

# Ansible can't support block retries, this is a relatively simple workaround
# to achieve the same thing
# https://github.com/ansible/ansible/issues/46203#issuecomment-556013701

- name: 'wait : Wait until all services are ready'
  block:
    - name: "wait : Set the retry count"
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count|int + 1 }}"
        services_count: 0
        ready_services_count: 0

    - name: "wait : Check CPDServices status"
      community.kubernetes.k8s_info:
        api_version: metaoperator.cpd.ibm.com/v1
        kind: CPDService
        namespace: "{{ cpd_meta_namespace }}"
      register: cpd_services_lookup

    - debug:
        msg: "{{item.status.status}}"
      with_items: "{{ cpd_services_lookup.resources }}"
      loop_control:
        label: "{{ item.metadata.name }} status = {{ item.status.status }}"

    - name: "wait : Check whether the services are ready yet"
      set_fact:
        services_count: "{{ services_count|int + 1 }}"
        ready_services_count: "{{ ready_services_count|int + 1 if (item.status.status == 'Ready') else ready_services_count|int}}"
      with_items: "{{ cpd_services_lookup.resources }}"
      loop_control:
        label: "{{ item.metadata.name }} status = {{ item.status.status }}"

    - name: "wait : Fail if one or more services were not ready"
      when: ready_services_count != services_count
      fail:
        msg: "[{{ retry_count }}/180] {{ ready_services_count }} of {{ services_count }} services are ready"
  rescue:
    - name: "wait : Give up after 120 attempts (approx 10 hours)"
      when: retry_count|int >= 120
      fail:
        msg: Timed out waiting for CPDServices to be ready

    - name: "wait : Wait for 5 minutes before checking again"
      pause:
        minutes: 5

    - include_tasks: wait_for_services.yml
